### ISSUE TITLE
Kibana service stops when basePath is set

### ISSUE THREAD

**Issue by rvolykh** [spujadas/elk-docker#176] opened 2017-11-03 14:16 UTC
Image: sebp/elk:520 (same for 563)

I'm trying to starting container with 'docker-compose' when kibana.yml contains `basePath`. Logstash and elastic runs well, but kibana is stopped. `service kibana restart` inside container help it to start, but after a while shutdowns. Configs is available inside container. 
But when i start kibana from container manually as binary `./opt/kibana/bin/kibana` everything works like a charm. After that even after stopping kibana (manually started) and starting `service kibana start` (as a service) everything work fine even after container restarts. 
Probably, some problems with cache. Can you please, suggest where to dig in.

Thanks,

----------
docker-compose.ymp
```
elk:
        image: sebp/elk:520
        ports:
            - "9200:9200"   #elasticsearch
            - "5601:5601"   #kibana
            - "5044:5044"   #logstash
        volumes:
            - "./conf/kibana/kibana.yml:/opt/kibana/config/kibana.yml"  # old (4.x) location
            - "./conf/kibana/kibana.yml:/etc/kibana/config/kibana.yml"  # new (5.x) location
```
kibana.yml
```
server:
  basePath: "/kibana"
  host: "0.0.0.0"
```
Kibana logs:
```
{"type":"log","@timestamp":"2017-11-03T14:01:49Z","tags":["info","optimize"],"pid":190,"message":"Optimiz
ing and caching bundles for kibana, timelion and status_page. This may take a few minutes"}
```

**Comment by spujadas** [comment] 2017-11-06 22:24
Will attempt to reproduce later this week, will keep you posted.

Having said that, from the description you gave, it's quite possible that the issue is not specific to this image, so you may want to try checking in with https://discuss.elastic.co/c/kibana in parallel.

**Comment by rvolykh** [comment] 2017-11-07 09:45
Hello, thanks, You are right - https://discuss.elastic.co/t/kibana-via-nginx-proxy/103920/3
there is same problem as I have, I will try put config directly in /opt/kibana/kibana.yml

**Comment by rvolykh** [comment] 2018-04-18 07:31
Hello Sebastient (@spujadas)
When kibana daemon starts I got such error (added verbose mode):
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/opt/kibana/bin/../node/bin/node]
 2: 0x109f13c [/opt/kibana/bin/../node/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/opt/kibana/bin/../node/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/opt/kibana/bin/../node/bin/node]
```
Looks like somehow kibana optimization process tooks more memory than 250 MB [81995 ms: Mark-sweep 242.8 (268.5) -> 243.9 (268.5) MB, 642.5 / 0.0 ms [last resort gc].]

Than I increased it value (NODE_OPTIONS="--max-old-space-size=128") to 512 it crash again with Process out of Memory, and when increased to 1024 kibana successfully started.

**Comment by spujadas** [comment] 2018-04-18 21:16
Thanks very much for the update!
(Closing the issue.)

**Closed by spujadas** 2018-04-18 21:16 UTC
