### ISSUE TITLE
can not start ELK

### ISSUE THREAD

**Issue by KeZhimin** [spujadas/elk-docker#262] opened 2019-04-02 07:56 UTC
![image](https://user-images.githubusercontent.com/7068010/55385068-e2b04380-555e-11e9-8719-570cb6ac54c2.png)
![image](https://user-images.githubusercontent.com/7068010/55385105-f2c82300-555e-11e9-866b-d12648e7203e.png)
![image](https://user-images.githubusercontent.com/7068010/55385134-01163f00-555f-11e9-919a-4e878162d197.png)
![image](https://user-images.githubusercontent.com/7068010/55385167-168b6900-555f-11e9-968d-fb126dc472ac.png)

![image](https://user-images.githubusercontent.com/7068010/55385234-3cb10900-555f-11e9-99f8-f39139557275.png)

the error message above，the console always print 
````
{"type":"log","@timestamp":"2019-04-02T07:40:01Z","tags":["warning","elasticsearch","admin"],"pid":274,"message":"Unable to revive connection: http://localhost:9200/"}
{"type":"log","@timestamp":"2019-04-02T07:40:01Z","tags":["warning","elasticsearch","admin"],"pid":274,"message":"No living connections"}
````
any wrong with my operation, i just use command in the document, the command is ``docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk``

the docker version is 18.09.4, the elk-docker version is latest.

**Comment by spujadas** [comment] 2019-04-03 20:48
Everything having seemed to start up properly, my guess is that the container ran out of memory and Elasticsearch was terminated (see https://elk-docker.readthedocs.io/#es-suddenly-stopping).

**Comment by jast90** [comment] 2019-05-05 12:46
> Everything having seemed to start up properly, my guess is that the container ran out of memory and Elasticsearch was terminated (see https://elk-docker.readthedocs.io/#es-suddenly-stopping).

I used GCP VM with 4  vCPU，15 GB RAM , and get the same error

**Comment by spujadas** [comment] 2019-05-05 13:22
> I used GCP VM with 4 vCPU，15 GB RAM , and get the same error

@jast90 as it seems you're not the OP of this issue, could you please post the container's output to confirm that the issue is indeed exactly the same?
Regardless, could you `docker exec` into the container and `ps aux` to have the list of running processes? Assuming that ES is not running, could you provide ES's logs?

**Comment by abalone49** [comment] 2019-07-17 15:45
Same problem here :

> 
[2019-07-17T15:23:43,235][INFO ][o.e.d.DiscoveryModule    ] [6mj-7It] using discovery type [zen] and host providers [settings]
[2019-07-17T15:23:44,293][INFO ][o.e.n.Node               ] [6mj-7It] initialized
[2019-07-17T15:23:44,293][INFO ][o.e.n.Node               ] [6mj-7It] starting ...
[2019-07-17T15:23:44,473][INFO ][o.e.t.TransportService   ] [6mj-7It] publish_address {172.17.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2019-07-17T15:23:44,707][INFO ][o.e.b.BootstrapChecks    ] [6mj-7It] bound or publishing to a non-loopback address, enforcing bootstrap checks
[2019-07-17T15:23:44,751][ERROR][o.e.b.Bootstrap          ] [6mj-7It] node validation exception
[1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2019-07-17T15:23:44,753][INFO ][o.e.n.Node               ] [6mj-7It] stopping ...
[2019-07-17T15:23:44,781][INFO ][o.e.n.Node               ] [6mj-7It] stopped
[2019-07-17T15:23:44,781][INFO ][o.e.n.Node               ] [6mj-7It] closing ...
[2019-07-17T15:23:44,794][INFO ][o.e.n.Node               ] [6mj-7It] closed
[2019-07-17T15:23:44,799][INFO ][o.e.x.m.p.NativeController] [6mj-7It] Native controller process has stopped - no new native processes can be started

**Comment by spujadas** [comment] 2019-07-17 18:50
@abalone49 nope, not actually the same problem as this issue, but yours is the same one as #287

**Closed** 2020-02-17 21:07 UTC
